### PR TITLE
support constants and normalize array in double quoted strings

### PR DESCRIPTION
**Pull request by jens1o**

### CODE REVIEW

**Comment by jens1o** [comment]
oh.

**Comment by Binaryify** [comment]
>This branch has conflicts that must be resolved
You should update your branch

**Comment by jens1o** [comment]
ok. I edited it online on GitHub.

**Comment by jens1o** [comment]
don't merge. I need to commit the constants too.

**Comment by Binaryify** [comment]
ok

**Comment by jens1o** [comment]
I'm done.

**Comment by jens1o** [comment]
you can publish now, at the moment I don't see any problem.

**Comment by Binaryify** [comment]
ok

**Comment by Binaryify** [comment]
I'm done too.

**Comment by jens1o** [comment]
In which way?

**Comment by Binaryify** [comment]
@jens1o 
Wait for minutes, my network has some trouble

**Comment by jens1o** [comment]
Don't hurry. 😉

**Comment by Binaryify** [comment]
@jens1o 
I'm done

**Pull request merged**
